### ISSUE TITLE
Wrong email at login is creating server error in UserDao

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [tagaprice/tagaprice#27]
if user is not available in the DB,  the UserDao should return false or a NoUserException. 
Now i get a 500 server error

**Comment by reihu** [comment]
Actually that was not an issue in the DAO but a NullPointerExeption caused by a missing check in LoginServiceImpl.setLogin().
The issue has been fixed in commit 06fe2ede81be69e55049
